### ISSUE TITLE
Issue with compatibility with Python 3.8

### ISSUE THREAD

**Issue by DanieTheron** [CNES/aviso-fes#12]
Hi Team,

I am using CoastSat by Killian Vos. An extension, called CoastSat.slope, makes use of aviso-fes for tidal correction. I see in the setup.py file that it states compatibility up till Python 3.10. However, when I try to install it with conda: conda install pyfes -c fbriol, it says that the environment is incompatible and requires a Python 3.7 environment (see attached photo). The issue is similar to #9.

**Specifications:

  - pyfes -> python[version='>=3.7,<3.8.0a0']**

Could you perhaps suggest a way I can install it in Python 3.8 environment?

![Compatibilty_Issue](https://user-images.githubusercontent.com/108867722/183964272-0531de16-6bf0-4d4f-b15d-254f9d22be78.png)

**Comment by fbriol** [comment]
This package is an old compilation that I had made for my needs. It is not up to date anymore. You have to compile a new version on your computer. To generate the Conda package, you just have to install conda-build and type at the root of the project ``conda build conda/``.

I have generated three packages for python 3.8, 3.9 and 3.10 for Linux on my [Anaconda account](https://anaconda.org/fbriol/pyfes).
