### ISSUE TITLE
Update of netcdf files

### ISSUE THREAD

**Issue by jouArc** [CNES/aviso-fes#14]
Hello,
Do we need also an updated version of the netcdf folder (ocean tide etc) to use this latest release of FES2022 with the new waves ?
I tried to look on aviso but it seems that nothing has been updated on FES2014 data.
Many thanks!

**Comment by fbriol** [comment]
This question is out of date. Please use the latest version of this software. You can install it from [Conda](https://cnes.github.io/aviso-fes/conda.html).
