### ISSUE TITLE
Problem installing from CONDA

### ISSUE THREAD

**Issue by Alerovere** [CNES/aviso-fes#15]
Hello, 
I am having a problem on the installation from CONDA. No matter what python version my environment is, I get this error:
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

I tried all python versions, from 2.7 to 3.10. Can you please point me to a solution? I probably am missing something very obvious here.

**Comment by fbriol** [comment]
I can't reproduce the mistake. Try to update your conda environment (conda update all -c conda-forge) then reinstall the library (conda install pyfes -c fbriol -c conda-forge)

**Comment by Alerovere** [comment]
Thanks, that did the trick. i feel a bit stupid for not thinking to update the env. once installed.
