### ISSUE TITLE
Compute Ocean Tide Loading

### ISSUE THREAD

**Issue by xwanner** [CNES/aviso-fes#16]
Hi all,

I am not familiar at all with tide products, but I am using the ocean tide loading derived from it for GNSS application.
For now, I compute the loadings from there : http://holt.oso.chalmers.se/loading/index.html
But is it possible to compute it with this API, and if so how ? I could include it in my processing chain, it would make the things much easier than manually generate those file through the Chalmers interface.

Thanks in advance for your help

Xavier Wanner

**Comment by fbriol** [comment]
This question is out of date. Please use the latest version of this software. You can install it from [Conda](https://cnes.github.io/aviso-fes/conda.html). They also have an updated tutorial on calculating the [ocean tide](https://cnes.github.io/aviso-fes/auto_examples/ex_prediction.html#sphx-glr-auto-examples-ex-prediction-py).
