### ISSUE TITLE
Bug / issue with import fes test

### ISSUE THREAD

**Issue by nicholasmetherall** [CNES/aviso-fes#2]
https://bitbucket.org/cnes_aviso/fes/issues/3/advice-on-installing-python-package

Thank you @Killian Vos, @fbriol  and others for the support on this. I am having some issues with the testing step ‘import pyfes’

ImportError: libnetcdf.so.15: cannot open shared object file: No such file or directory

Yet the directory does seem to exist as it has been saved on the python directory and on the desktop and is readable in the same notebook:

dir ('/common/tidal_models')

Any advice about how to progress to the next step would be much appreciated.

**Comment by zhy162** [comment]
@tovogt Hi, I couldn't find libnetcdf=7.8.3 in my usual conda channels. Do you know where can I install it?

**Comment by fbriol** [comment]
This package is an old compilation that I had made for my needs. It is not up to date anymore. You have to compile a new version on your computer. To generate the Conda package, you just have to install conda-build and type at the root of the project ``conda build conda/``.

I have generated three packages for python 3.8, 3.9 and 3.10 for Linux on my [Anaconda account](https://anaconda.org/fbriol/pyfes).
