### ISSUE TITLE
Conda package for osx-arm64?

### ISSUE THREAD

**Issue by peanutfun** [CNES/aviso-fes#20]
I cannot install pyfes because the package is only available for osx-64 architecture, but not osx-arm64. Unfortunately, this issue is obscured by the error message, which always reports that the package cannot be found:

```
$ mamba install pyfes -c fbriol

Looking for: ['pyfes']

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
pkgs/r/osx-arm64                                              No change
pkgs/main/noarch                                              No change
pkgs/r/noarch                                                 No change
pkgs/main/osx-arm64                                           No change
fbriol/noarch                                                 No change
fbriol/osx-arm64                                              No change

Pinned packages:
  - python 3.10.*


Could not solve for environment specs
The following package could not be installed
└─ pyfes does not exist (perhaps a typo or a missing channel).
```

Since Apple switched to the arm64 architecture for its computers, there is a growing number of users that require software built for this architecture. Are there any plans to release pyfes packages compatible to arm64 on conda?

**Comment by FlorisCalkoen** [comment]
Any updates on this issue? We would be very glad incorporate the FES14 tide model in our teaching material, but currently this Mac osx-arm64 issue is breaking our build.

**Comment by peanutfun** [comment]
I found this information on cross-compiling packages for conda-forge, but I am not familiar enough with neither the setup of this repository nor conda-forge to come up with a PR: https://conda-forge.org/blog/2020/10/29/macos-arm64/

**Comment by FlorisCalkoen** [comment]
I'm afraid the same holds for me. I'll see if I can do a little read up in the next days. Also I contacted someone I know at CNES to ask who is currently managing the PyFES builds. From somebody else I heard rumors that they are preparing a PyFES22 library, which is supposed to be more robust.

**Comment by fbriol** [comment]
This question is out of date. Please use the most recent version of this software. You can install it from [Conda](https://cnes.github.io/aviso-fes/conda.html). The ARM package should be available soon.

**Comment by peanutfun** [comment]
`conda install -c conda-forge pyfes` works as expected for Python 3.10+. Thanks a lot for the update @fbriol!
