### ISSUE TITLE
How to run pyfes?

### ISSUE THREAD

**Issue by slimgana** [CNES/aviso-fes#21]
Hi All,
This is my first attempt to use pyfes.
Is there any user guide to learn how to run pyfes in a given area of the world?
If not, is there anyone who could kindly give the outline of the procedure to run pyfes?
Thank you.

**Comment by fbriol** [comment]
This question is out of date. Please use the latest version of this software. You can install it from [Conda](https://cnes.github.io/aviso-fes/conda.html). They also have an updated tutorial on calculating the [ocean tide](https://cnes.github.io/aviso-fes/auto_examples/ex_prediction.html#sphx-glr-auto-examples-ex-prediction-py).
