### ISSUE TITLE
run cmake pointing it to the source directory

### ISSUE THREAD

**Issue by AimAlee** [CNES/aviso-fes#22]
Building & Installing
One nice and highly recommended feature of CMake is the ability to do out of source builds. In this way you can make all your .o files, various temporary depend files, and even the binary executables without cluttering up your source tree. To use out of source builds, first create a build directory, then change into your build directory and **run cmake pointing it to the source directory**:

mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/opt/local

Hi, which is the source directory? Is it aviso-fes code folder which contains CMakeLists.txt? Please guide.

If I run this command (cmake .. -DCMAKE_INSTALL_PREFIX=/opt/local) it responts that the build directory does not contain CMakeLists.txt.

please

**Comment by fbriol** [comment]
This question is out of date. Use the latest version of this software. You can install it from [Conda](https://cnes.github.io/aviso-fes/conda.html)

**Comment by AimAlee** [comment]
> This question is out of date. Use the latest version of this software. You can install it from [Conda](https://cnes.github.io/aviso-fes/conda.html)

Thank you very much. It worked.
