### ISSUE TITLE
Is the data for SA and SSA different from that in Figure 4 of paper

### ISSUE THREAD

**Issue by KuifengZhao** [CNES/aviso-fes#25]
Reference paper: FES2014 global ocean tide atlas: design and performance
The data in Figure 4 shows max of 0.11m for SA and 0.042m for SSA component, But the data in the sa.nc and ssa.nc files of this github dataset has a much smaller values (i.e., 0.043 and 1.78) with label of unit as 'cm'. 

Could you please help check what might be the reason for the difference? Thank you very much.

**Comment by fbriol** [comment]
The file included in the distribution is not the official version of FES2014, but a very old version FES99. You need to download the atlas from the [AVISO website](https://www.aviso.altimetry.fr/en/data/products/auxiliary-products/global-tide-fes.html)
