### ISSUE TITLE
failed install via anaconda

### ISSUE THREAD

**Issue by ricsatjr** [CNES/aviso-fes#3]
I keep getting the following results after following your installation instructions:

(coastsat) bach@bach-aspirea51556:~/Git/coastsat/CoastSat$ conda install -c fbriol pyfes
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
...

**Comment by fbriol** [comment]
This package is an old compilation that I had made for my needs. It is not up to date anymore. You have to compile a new version on your computer. To generate the Conda package, you just have to install conda-build and type at the root of the project ``conda build conda/``.

I have generated three packages for python 3.8, 3.9 and 3.10 for Linux on my [Anaconda account](https://anaconda.org/fbriol/pyfes).
