### ISSUE TITLE
Problems with harmonic analysis if full list of constituents is not given explicitly in initializing WaveTable

### ISSUE THREAD

**Issue by cseaton** [CNES/aviso-fes#36]
Using the example case of conducting harmonic analysis on a time series, if the WaveTable is initialized with anything other than the explicit full list of constituents, the harmonic analysis fails. If WaveTable is initialized with an explicit short list of constituents, then compute_nodal_modulations() fails with an Index Error for the missing constituents from the default full list. If the table is initialized without specifying the list of constituents, then compute_nodal_modulations() and harmonic_analysis() run without error, but the results are entirely NaN.

```python
import pyfes
import numpy as np
time=np.arange(np.datetime64('2018-01-01'),np.datetime64('2018-03-01'), 3600, dtype='datetime64[s]') #generate 60 days of hourly times 
h = np.random.rand(time.shape[0])  #generate placeholder junk tide data
leap_seconds = pyfes.get_leap_seconds(time)  

# example with short list of constituents
wt = pyfes.WaveTable(['M2','S2','N2','K1','O1','Q1'])  # WaveTable for analysis of 6 constituents
f, vu = wt.compute_nodal_modulations(time, leap_seconds)  # code fails here with IndexError for 'Mm' constituent
w = wt.harmonic_analysis(h,f,vu)

# example with default list of constituents
wt = pyfes.WaveTable()  # WaveTable for analysis of 6 constituents
f, vu = wt.compute_nodal_modulations(time, leap_seconds)  
w = wt.harmonic_analysis(h,f,vu)  # values in w are entirely nan

# example with default list of constituents given explicitly (from example)
wt = pyfes.WaveTable([
    'Mm', 'Mf', 'Mtm', 'Msqm', '2Q1', 'Sigma1', 'Q1', 'Rho1', 'O1', 'MP1',
    'M11', 'M12', 'M13', 'Chi1', 'Pi1', 'P1', 'S1', 'K1', 'Psi1', 'Phi1',
    'Theta1', 'J1', 'OO1', 'MNS2', 'Eps2', '2N2', 'Mu2', '2MS2', 'N2', 'Nu2',
    'M2', 'MKS2', 'Lambda2', 'L2', '2MN2', 'T2', 'S2', 'R2', 'K2', 'MSN2',
    'Eta2', '2SM2', 'MO3', '2MK3', 'M3', 'MK3', 'N4', 'MN4', 'M4', 'SN4',
    'MS4', 'MK4', 'S4', 'SK4', 'R4', '2MN6', 'M6', 'MSN6', '2MS6', '2MK6',
    '2SM6', 'MSK6', 'S6', 'M8', 'MSf', 'Ssa', 'Sa'
]) 
f, vu = wt.compute_nodal_modulations(time, leap_seconds)  
w = wt.harmonic_analysis(h,f,vu)  # values in w are valid
```

According to the example text, I would expect either of these ways to initialize the WaveTable to work and to produce valid harmonic analysis results in w. When no list is provided, the full list should be used, and when a short list is provided, only those constituents should be used in the analysis.

Pyfes version: 2024.6.0
Numpy version: 2.1.3
Python version: 3.11.10 | packaged by conda-forge | (main, Oct 16 2024, 01:27:36) [GCC 13.3.0]

**Comment by fbriol** [comment]
Thank you for reporting the problem. It has been fixed in the development version. The fix will be included in the next version.
