### ISSUE TITLE
usage with complete fes2014 ocean_tide files

### ISSUE THREAD

**Issue by ezaron** [CNES/aviso-fes#4]
Hello:
I am trying to use the example/fes_slev.c program to generate tide predictions with the FES2014 data files I downloaded in 2019.

I have adapted the fes_slev.c program to point to the .ini files that came with the FES2014 donwload. When I run the program, the tide predictions are very different from the tide predictions generated from example data in this git repository under test/data. I wonder if you can provide an example output of fes_slev.c which uses the full FES2014 model?

Here is the output of fes_slev.c when I use the full FES2014 ocean_tide and load_tide fields:
build/examples$ ./fes_slev_edz 
      JulDay  Hour  Latitude Longitude Short_tid    LP_tid Pure_Tide  Geo_Tide  Rad_Tide
 12053.00000     0    59.195    -7.688   -92.831     1.014   -91.817   -89.047     2.769
 12053.04167     1    59.195    -7.688  -131.850     0.987  -130.863  -127.487     3.376
 12053.08333     2    59.195    -7.688  -137.119     0.959  -136.160  -133.091     3.069
 12053.12500     3    59.195    -7.688  -107.177     0.931  -106.246  -104.324     1.922
 12053.16667     4    59.195    -7.688   -48.534     0.902   -47.632   -47.419     0.213
 12053.20833     5    59.195    -7.688    25.530     0.873    26.403    24.763    -1.640
 12053.25000     6    59.195    -7.688    96.132     0.843    96.975    93.827    -3.148
 12053.29167     7    59.195    -7.688   144.123     0.812   144.935   141.044    -3.891
 12053.33333     8    59.195    -7.688   157.545     0.782   158.326   154.652    -3.674
 12053.37500     9    59.195    -7.688   134.338     0.750   135.089   132.514    -2.575
 12053.41667    10    59.195    -7.688    80.504     0.718    81.222    80.356    -0.866
 12053.45833    11    59.195    -7.688     8.294     0.686     8.980    10.042     1.062
 12053.50000    12    59.195    -7.688   -65.386     0.653   -64.733   -61.967     2.766
 12053.54167    13    59.195    -7.688  -122.488     0.620  -121.868  -118.035     3.833
 12053.58333    14    59.195    -7.688  -149.138     0.586  -148.551  -144.551     4.000
 12053.62500    15    59.195    -7.688  -139.819     0.552  -139.267  -136.029     3.237
 12053.66667    16    59.195    -7.688   -97.658     0.518   -97.140   -95.398     1.742
 12053.70833    17    59.195    -7.688   -32.831     0.483   -32.348   -32.466    -0.118
 12053.75000    18    59.195    -7.688    38.184     0.448    38.632    36.756    -1.876
 12053.79167    19    59.195    -7.688    95.824     0.413    96.237    93.175    -3.062
 12053.83333    20    59.195    -7.688   124.784     0.378   125.162   121.785    -3.378
 12053.87500    21    59.195    -7.688   119.168     0.342   119.511   116.723    -2.788
 12053.91667    22    59.195    -7.688    81.910     0.306    82.216    80.727    -1.489
 12053.95833    23    59.195    -7.688    22.556     0.270    22.826    23.006     0.179

The netcdf header of the ocean_tide/m2.nc file reports this (from files downloaded in 2019):

// global attributes:
                string :cdm_data_type = "Grid" ;
                string :license = "http://www.aviso.oceanobs.com/fileadmin/documents/data/License_Aviso.pdf" ;
                string :title = "FES2014b tide elevations" ;
                string :product_version = "b" ;
                string :summary = "global tide solution using finite element mesh, T-UGO barotropic model and data assimilation of altimetry and tidal gauges" ;
                string :project = "FES2014" ;
                string :credits = "LEGOS, NOVELTIS, CLS, CNES" ;
                string :contact = "aviso@oceanobs.com" ;
                string :references = "http://www.aviso.altimetry.fr/en/data/products/auxiliary-products/global-tide-fes/description-fes2014.html" ;
                string :date_created = "2016-10-20 12:34:35" ;
                string :history = "2016-10-20 12:34:35:creation" ;
                string :Conventions = "CF-1.6" ;
                string :geospatial_lat_units = "degrees_north" ;
                string :geospatial_lon_units = "degrees_east" ;
                :geospatial_lat_resolution = 0.0625 ;
                :geospatial_lon_resolution = 0.0625 ;

Can you provide check values so I can verify if I am using the software correctly with the full FES2014 fields?

-Ed

**Comment by fbriol** [comment]
I added an example of output with the [FES2014 v1.2](https://github.com/CNES/aviso-fes/blob/8e3a512c92a87684c068feb8c925f49a6f5bde9a/examples/fes_slev_2014_v1.2.txt) grids. The example file had not been updated since 2016. I did it.

Frederic.
