### ISSUE TITLE
Dependency on libnetcdf==4.7.3 (libnetcdf.so.15) is causing problems with other packages

### ISSUE THREAD

**Issue by turekg** [CNES/aviso-fes#8]
The current (2.9.2) version of pyfes will not work if libnetcdf.so.15 (linux)/libnetcdf.15.dylib (MacOSX) is not present. This is causing all sorts of headaches with library conflicts, notably geopandas which requires a newer libnetcdf (4.8.1)

**Comment by fbriol** [comment]
This package is an old compilation that I had made for my needs. It is not up to date anymore. You have to compile a new version on your computer. To generate the Conda package, you just have to install conda-build and type at the root of the project ``conda build conda/``.

I have generated three packages for python 3.8, 3.9 and 3.10 for Linux on my [Anaconda account](https://anaconda.org/fbriol/pyfes).
