### ISSUE TITLE
compatibility with Python 3.8

### ISSUE THREAD

**Issue by kvos** [CNES/aviso-fes#9]
Hi team, 

Firstly really thankful for this great package, have been using it for a number of years (when back on bitbucket) and it works perfectly.
I maintain another toolbox ([CoastSat](https://github.com/kvos/CoastSat)) which uses pyfes to get tide levels for tidally-correcting satellite-derived shorelines. I have recently moved my environment to Python 8 and found out that the pyfes package is only compatible with Python 7. Would it be possible to add compatibility with Python 8? 
Thanks,
Kilian

**Comment by fbriol** [comment]
The latest version is compatible up to Python 3.10.
